- tap:
    - homebrew/cask-fonts

- brew:
    - git
    - git-flow
    - lazygit
    - neovim
    - font-jetbrains-mono-nerd-font
    - eza
    - fzf

- cask:
    - alex313031-thorium
    - raycast
    - wechat
    - douyin
    - neteasemusic

