- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- link:
    ~/.config/nvim: neovim
    ~/.zshenv: shell/zsh/.zshenv
    ~/.config/zsh: shell/zsh
    ~/.config/joshuto: joshuto
    ~/.config/kitty: kitty

