- link:
    ~/Library/Rime/:
      glob: true
      path: rime/rime-ice/*

- tap:
    - homebrew/cask-fonts

- brew:
    - git
    - git-flow
    - lazygit
    - neovim
    - font-jetbrains-mono-nerd-font
    - eza
    - fzf
    - joshuto
    - poppler

- cask:
    - alex313031-thorium
    - raycast
    - wechat
    - douyin
    - neteasemusic
    - obsidian
    - kitty
    - squirrel

