- defaults:
    link:
      create: true
      relink: true

- link:
    # ssh
    ~/.ssh/id_ed25519: ../Secrets/ssh/id_ed25519
    ~/.ssh/id_ed25519.pub: ../Secrets/ssh/id_ed25519.pub
    # git
    ~/.gitconfig: shell/git/.gitconfig-win
    # python
    ~/AppData/Roaming/pip/pip.ini: shell/python/pip.ini

    # Clash
    ~/.config/clash: ../Secrets/clash
    # Listary
    ~/AppData/Roaming/Listary/UserProfile/Settings/Preferences.json: apps/listary/UserProfile/Settings/Preferences.json
    ~/AppData/Roaming/Listary/UserProfile/UserFiles: apps/listary/UserProfile/UserFiles
    # everything
    ~/AppData/Roaming/Everything: apps/everything/everything
    C:/Program Files/Everything:
        glob: true
        path: apps/everything/everythinglib/*
    # Rime
    ~/AppData/Roaming/Rime:
        glob: true
        path: apps/rime/rime-ice/*
    
    # Wechat Files
    ~/Documents/WeChat Files: ../ProgramData/WeChat Files
    ~/Documents/WXWork: ../ProgramData/WXWork
    # Total Commander
    ~/AppData/Local/TotalCMD64: ../ProgramData/TotalCMD64
    # typora
    ~/AppData/Roaming/Typora/themes: ../ProgramData/Typora/themes

- shell:
  - [regedit /s desktop\windows\Registry\UTC.reg]
  - [regedit /s desktop\windows\Registry\Origin2021.reg]
  - [regedit /s desktop\windows\Registry\TotalCommander.reg]
