- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- link:
    ~/.config/nvim: neovim
    ~/.zshenv: zsh/.zshenv
    ~/.config/zsh: zsh
    ~/.config/ranger: ranger
    ~/.config/joshuto: joshuto

