- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- link:
    ~/.zshenv: shell/zsh/.zshenv
    ~/.config/zsh: shell/zsh
    ~/.config/nvim: cli-apps/neovim
    ~/.config/joshuto: cli-apps/joshuto
    ~/.config/kitty: kitty

