- defaults:
    link:
      create: true
      relink: true

- link:
    # ssh
    ~/.ssh/id_ed25519: ../Secrets/ssh/id_ed25519
    ~/.ssh/id_ed25519.pub: ../Secrets/ssh/id_ed25519.pub
    # git
    ~/.gitconfig: shell/git/.gitconfig-win
    # python
    ~/AppData/Roaming/pip/pip.ini: shell/python/pip.ini

    # Listary
    ~/AppData/Roaming/Listary/UserProfile/Settings/Preferences.json: apps/listary/UserProfile/Settings/Preferences.json
    ~/AppData/Roaming/Listary/UserProfile/UserFiles: apps/listary/UserProfile/UserFiles
    # everything
    ~/AppData/Roaming/Everything: apps/everything/everything
    C:/Program Files/Everything:
        glob: true
        path: apps/everything/everythinglib/*
